[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["chat_with_nerf"]

[project]
name = "chat_with_nerf"
version = "0.1.0"
description = "Chat with NeRF"
readme = "README.md"
requires-python = ">=3.10.0"
license = { text="Apache 2.0"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
]

dependencies = [
    "glob2==0.7",
    "setuptools>=67.7.2",
    "pathtools>=0.1.2",
    "promise>=2.3",
    "pybind11>=2.10.4",
    "pyyaml>=6.0",
    "numpy>=1.24.3",
    "attrs>=23.1.0",
    "omegaconf>=2.3.0",
    "gradio>=3.30.0",
    "torch",
    "Pillow>=9.5.0",
    "torchtyping",
    "nerfstudio>=0.3.0",
    "lerf>=0.1.0",
    "cattrs",
    "types-requests",
    "einops==0.6.1",
    "h5py==3.8.0",
    "scikit-learn==1.2.2",
    "trimesh==3.21.7"
]

[project.optional-dependencies]

dev = [
    "black",
    "flake8",
    "isort",
    "mypy",
    "gitlint",
    "pre-commit",
    "pytest",
    "pytest-mock",
    "ipdb",
    "types-Pillow",
    "types-PyYAML",
    "types-requests",
    "types-urllib3"
]
