[tool.pylint."messages control"]
disable = [
    "duplicate-code",
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
]

[tool.pylint.design]
max-args = 8
max-locals = 18
max-attributes = 10
max-public-methods = 30


[tool.pydocstyle]
inherit = false
# Ignore missing docstrings for now, but existing docstrings must be correct.
ignore = ["D1", "D203", "D213"]

[tool.mypy]
ignore_missing_imports = true
