[tool.black]
target-version = ["py39"]

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
combine_as_imports = true
force_sort_within_sections = true
forced_separate = [
  "tests",
]
known_first_party = [
  "hassapi",
  "appdaemon",
]

[tool.pylint.MASTER]
jobs = 4
load-plugins = [
  "pylint.extensions.code_style",
  "pylint.extensions.typing",
]
persistent = false

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "attribute-defined-outside-init",
  "import-outside-toplevel",
  "wrong-import-position",
]

[tool.pylint.BASIC]
class-const-naming-style = "any"
good-names = [
  "_",
  "ev",
  "ex",
  "fp",
  "i",
  "id",
  "j",
  "k",
  "Run",
  "T",
]

[tool.pylint.REPORTS]
score = true

[tool.pylint.TYPECHECK]

[tool.pylint.FORMAT]
expected-line-ending-format = "LF"

[tool.pylint.TYPING]
py-version = "3.9"
runtime-typing = false
