[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 120

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20