[tool.black]
line-length = 79
target-version = ['py39']
include = '\.py?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | tests
  | lcl
  | alembic
  | pagure/hooks/files

)/
'''

