[tool.poetry]
name = "AutoNode"
version = "0.1.0"
description = ""
authors = ["SuperAGI"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
kombu = "^5.3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
